# culture="en-US"

ConvertFrom-StringData @'
   Loading = Loading Project Presto GUI...
   FoundVars = Found global variables file...
   VarsMissing = Global Configuration (GlobalVariables1.ps1) missing in $RunPath! Script execution cannot continue!
   LoadVars = Loading global variables file...
   FoundHTML = Found HTML code file...
   HTMLMissing = The HTML code file (HTMLCode.ps1) missing. Script execution cannot continue!
   LoadHTML = Loading HTML code file...
   WindowTitle = Project Presto GUI .:. Alpha Version .:. Work In Progress
   SwitchThema = You can now switch theme between light and dark.
   butSwitch = Switch Theme
'@