# culture="nl-NL"

ConvertFrom-StringData @'
	Loading = Project Presto GUI wordt geladen...
    FoundVars = Het variabelenbestand is gevonden...
    VarsMissing = De globale variablenlijst (GlobalVariables.ps1) ontbreekt. Het script kan niet uitgevoerd worden!
    LoadVars = De globale variablenlijst wordt geladen...
    FoundHTML = Het HTML code bestand is gevonden...
    HTMLMissing = Het HTML code bestand (HTMLCode.ps1) ontbreekt. Het script kan niet uitgevoerd worden!
    LoadHTML = Het HTML code bestand wordt geloaden...
    WindowTitle = Project Presto GUI .:. Alpha Versie .:. Er wordt nog aan gewerkt
    SwitchThema = U kan nu omschakelen tussen een licht of donker thema.
    butSwitch = Thema Omschakelen
'@